### ISSUE TITLE
Package fails to build on r-release-macos-x86_64 at CRAN

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppsimdjson#101]
R 4.6.0 is now out and defaults to C++20 unless something else is specified.  That is fine.

Unless the machine use is too old, and it appears that r-release-macos-x86_64 is one such machine as per [the overview table](https://cran.r-project.org/web/checks/check_flavors.html#r-release-macos-x86_64) it runs clang++-14 on macOS-13.3.1.  This now results in

```
clang++ -arch x86_64 -std=gnu++20 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Volumes/Builds/packages/big-sur-x86_64/Rlib/4.6/Rcpp/include' -I/opt/R/x86_64/include   -DSIMDJSON_NO_COMPUTED_GOTO -I../inst/include  -fPIC  -falign-functions=64 -Wall -g -O2   -c simdjson_example.cpp -o simdjson_example.o
In file included from rcppsimdjson_utils_check.cpp:3:
In file included from ../inst/include/RcppSimdJson.hpp:5:
In file included from ../inst/include/RcppSimdJson/deserialize.hpp:5:
In file included from ../inst/include/RcppSimdJson/deserialize/simplify.hpp:5:
In file included from ../inst/include/RcppSimdJson/deserialize/../common.hpp:145:
../inst/include/RcppSimdJson/../simdjson.h:3081:10: error: expected concept name with optional arguments
    } -> std::convertible_to<typename std::remove_cvref_t<T>::value_type>;
         ^
In file included from simdjson_example.cpp:6:
../inst/include/simdjson.h:3081:10: error: expected concept name with optional arguments
    } -> std::convertible_to<typename std::remove_cvref_t<T>::value_type>;
         ^
../inst/include/RcppSimdJson/../simdjson.h:3102:8: error: no member named 'ranges' in namespace 'std'
  std::ranges::input_range<T> && !string_like<T> && !concepts::string_view_keyed_map<T>;
  ~~~~~^
../inst/include/RcppSimdJson/../simdjson.h:3102:28: error: 'T' does not refer to a value
  std::ranges::input_range<T> && !string_like<T> && !concepts::string_view_keyed_map<T>;
                           ^
../inst/include/RcppSimdJson/../simdjson.h:3100:20: note: declared here
template <typename T>
                   ^
```

and more lines like it --- while r-oldrel-macos-x86_64 is fine _with the same operating system and compiler_.  

So a fix may be to detect 'Darwin' and 'x86_64' and then switch to C++17.

**Comment by lemire** [comment]
We fully support C++20 and more. Node.js is built with simdjson and it defaults with C++20.

It is likely that the compiler is lying about what it supports. Ah AH. Let me see if I can't trace it.

**Comment by eddelbuettel** [comment]
Hi @lemire that is not you methinks or else I would have pinged you for help. 

See the branch [feature/macos13_cxx17](https://github.com/eddelbuettel/rcppsimdjson/tree/feature/macos13_cxx17) for a "fix" of reverting to C++17.  This particular machine uses a combination of
- clang++14
- the Apple SDK setting to support macos11 (yeah right)
- an R 4.6.0 choice to default to C++20 everywhere as a default

And that just doesn't work together.  (Note that the same machine and SDK setting works with R 4.5.* aka 'r-oldrel' where the default is still C++17).  I have an ongoing private email thread with members of the R Core team, and I want them to own this.  The simplest fix for us is to switch to C++17.  I do not think it is worth update code changes. I could be wrong.

(And I will try to catch up to 4.6.3 from you.)

**Comment by lemire** [comment]
So Ubuntu 22 seems to come with clang 14 by default. and things work out...

<img width="1042" height="90" alt="Image" src="https://github.com/user-attachments/assets/1e7bd82a-5b8e-476a-8910-2c19c384e957" />

<img width="1178" height="45" alt="Image" src="https://github.com/user-attachments/assets/9845f5b1-2510-4068-b5b7-4e0941dbb0ab" />

So it seems likely that you have a system mismatch.

(I know you did not ping me, but I am semi-obsessive about making things work out of the box.)

>  I do not think it is worth update code changes. I could be wrong.

Upgrading with C++20 makes many things nicer for the users of simdjson, but I don't think existing code will benefit. I could be wrong.

> (And I will try to catch up to 4.6.3 from you.)

I am currently waiting for LLVM to catch up with C++26 and we'll do a major release (likely 5.0). Currently, we have GCC 16... (it has excellent C++26 support) but I want to test our C++26 features with an official LLVM release.

**Comment by eddelbuettel** [comment]
Ubuntu is not relevant.  I do not think i mentioned Ubuntu anywhere here.  [ Oh sorry, I see where you were coming from.  I think I may even have done the same test here in a container.  It is not clang14 'per se', it is the setup of that box. ]

The machine in question is r-release-macos-x86_64, see [the overview table](https://cran.r-project.org/web/checks/check_flavors.html#r-release-macos-x86_64) linked to in line two above.

**Comment by eddelbuettel** [comment]
Further, we also look good 'on more normal systems' across Linux, macOS, windows at e.g. [our r-universe page](https://eddelbuettel.r-universe.dev/RcppSimdJson) with these builds (screenshot from the link just given)

<img width="1107" height="428" alt="Image" src="https://github.com/user-attachments/assets/32ef6370-673d-47e9-ae54-f8ea02140f19" />

Again, this is as best as I can tell a "them issue" not an "us" issue.  "They" imposed C++20 possibly without realizing when they did it that not all of their systems would cope.  The macoOS13 with SDK setting they have does not.

**Comment by lemire** [comment]
@eddelbuettel To clarify, I fully understood the issue, I think. What I did was to test it manually on clang++14.

I have no easy way to launch macOS systems with different configurations. But I use docker and various linux distributions.

This does not help you, but it helps me to know that we are not broken under LLVM 14 as supported by Ubuntu.


(We have a vast range of CI runs, but we don't test everything.)

**Comment by eddelbuettel** [comment]
@lemire All good, we are squarely on the same page.

Part of my private email chain with R Core was to convince to pretty-please not do exactly that: have it fail on a system nobody can reproduce.  Even r-universe which still bothers with macOS-13 on x86_64 uses a newer SDK setting for a newer build variant and copes.  

Sorry if I made alarming smoke. I tried to be surgical in the Subject: above and thereby avoiding to cast too wide a net.

**Comment by eddelbuettel** [comment]
The CRAN machine now picks C++17 when it sees this package so we can close this.
